// track-lab-data.jsx
// Aggregated 7-day Lab data + sessions list with shot data per session.
// Coord system MATCHES post-session-shotchart.jsx + track-lab-shotchart.jsx
// (natural SVG, y down, baseline y=0, half-court y=130).
// All shots are deterministically generated to fall strictly within their
// declared zones (rejection-sampled against arc + paint + corner geometry).

window.TL_DATA = {
  hot: {
    label: "Last 7 days",
    fg: 47,
    fgDelta: +6,
    made: 89,
    att: 189,
    sessions: 5,
    pps: 1.18,
    bestStreak: 8,
    verdict: "Right wing is on fire.",
    hotZone: "rw",
    shots: [
      { x:   4, y:   8, made: true, zone: "lc" },
      { x:   5, y:   3, made: true, zone: "lc" },
      { x:   4, y:  12, made: true, zone: "lc" },
      { x:   9, y:  11, made: true, zone: "lc" },
      { x:   7, y:   3, made: false, zone: "lc" },
      { x:   9, y:   6, made: false, zone: "lc" },
      { x:   9, y:   4, made: false, zone: "lc" },
      { x:   8, y:   4, made: false, zone: "lc" },
      { x:  17, y:  39, made: true, zone: "lw" },
      { x:  16, y:  43, made: true, zone: "lw" },
      { x:   1, y:  38, made: true, zone: "lw" },
      { x:  16, y:  69, made: true, zone: "lw" },
      { x:  10, y:  64, made: true, zone: "lw" },
      { x:   2, y:  45, made: true, zone: "lw" },
      { x:  20, y:  58, made: false, zone: "lw" },
      { x:  18, y:  38, made: false, zone: "lw" },
      { x:  17, y:  58, made: false, zone: "lw" },
      { x:  18, y:  50, made: false, zone: "lw" },
      { x:  27, y:  71, made: false, zone: "lw" },
      { x:  44, y:  71, made: false, zone: "lw" },
      { x:   8, y:  29, made: false, zone: "lw" },
      { x:  16, y:  37, made: false, zone: "lw" },
      { x:   4, y:  50, made: false, zone: "lw" },
      { x:  26, y:  50, made: false, zone: "lw" },
      { x:   4, y:  29, made: false, zone: "lw" },
      { x:  22, y:  54, made: false, zone: "lw" },
      { x:   8, y:  47, made: false, zone: "lw" },
      { x:  80, y:  92, made: true, zone: "top" },
      { x: 100, y:  75, made: true, zone: "top" },
      { x: 110, y: 119, made: true, zone: "top" },
      { x:  85, y:  90, made: true, zone: "top" },
      { x: 110, y:  95, made: true, zone: "top" },
      { x:  95, y:  88, made: true, zone: "top" },
      { x:  92, y: 102, made: true, zone: "top" },
      { x: 100, y: 110, made: true, zone: "top" },
      { x:  84, y: 107, made: false, zone: "top" },
      { x:  74, y: 122, made: false, zone: "top" },
      { x:  75, y: 105, made: false, zone: "top" },
      { x:  89, y: 104, made: false, zone: "top" },
      { x:  70, y:  91, made: false, zone: "top" },
      { x:  75, y:  95, made: false, zone: "top" },
      { x: 115, y: 115, made: false, zone: "top" },
      { x:  95, y: 125, made: false, zone: "top" },
      { x:  98, y: 123, made: false, zone: "top" },
      { x:  80, y: 120, made: false, zone: "top" },
      { x: 188, y:  28, made: true, zone: "rw" },
      { x: 185, y:  31, made: true, zone: "rw" },
      { x: 169, y:  68, made: true, zone: "rw" },
      { x: 177, y:  26, made: true, zone: "rw" },
      { x: 160, y:  61, made: true, zone: "rw" },
      { x: 165, y:  57, made: true, zone: "rw" },
      { x: 184, y:  41, made: true, zone: "rw" },
      { x: 178, y:  60, made: true, zone: "rw" },
      { x: 182, y:  37, made: true, zone: "rw" },
      { x: 169, y:  70, made: true, zone: "rw" },
      { x: 179, y:  62, made: true, zone: "rw" },
      { x: 167, y:  60, made: true, zone: "rw" },
      { x: 158, y:  66, made: true, zone: "rw" },
      { x: 170, y:  45, made: true, zone: "rw" },
      { x: 170, y:  67, made: true, zone: "rw" },
      { x: 184, y:  21, made: true, zone: "rw" },
      { x: 171, y:  64, made: false, zone: "rw" },
      { x: 174, y:  71, made: false, zone: "rw" },
      { x: 175, y:  55, made: false, zone: "rw" },
      { x: 160, y:  63, made: false, zone: "rw" },
      { x: 185, y:  58, made: false, zone: "rw" },
      { x: 163, y:  56, made: false, zone: "rw" },
      { x: 184, y:   4, made: true, zone: "rc" },
      { x: 188, y:   8, made: true, zone: "rc" },
      { x: 181, y:  11, made: false, zone: "rc" },
      { x: 183, y:   7, made: false, zone: "rc" },
      { x: 182, y:   7, made: false, zone: "rc" },
      { x: 182, y:  11, made: false, zone: "rc" },
      { x: 181, y:   5, made: false, zone: "rc" },
      { x:  31, y:   4, made: true, zone: "ml" },
      { x:  50, y:  38, made: true, zone: "ml" },
      { x:  49, y:  13, made: true, zone: "ml" },
      { x:  42, y:  25, made: true, zone: "ml" },
      { x:  55, y:  18, made: false, zone: "ml" },
      { x:  50, y:  26, made: false, zone: "ml" },
      { x:  57, y:  32, made: false, zone: "ml" },
      { x:  45, y:  30, made: false, zone: "ml" },
      { x:  60, y:  25, made: false, zone: "ml" },
      { x:  48, y:  12, made: false, zone: "ml" },
      { x:  67, y:  33, made: false, zone: "ml" },
      { x:  47, y:  11, made: false, zone: "ml" },
      { x:  39, y:   8, made: false, zone: "ml" },
      { x: 141, y:   7, made: true, zone: "mr" },
      { x: 142, y:  40, made: true, zone: "mr" },
      { x: 141, y:   4, made: true, zone: "mr" },
      { x: 135, y:  18, made: true, zone: "mr" },
      { x: 145, y:  30, made: false, zone: "mr" },
      { x: 130, y:  14, made: false, zone: "mr" },
      { x: 130, y:  25, made: false, zone: "mr" },
      { x: 142, y:  12, made: false, zone: "mr" },
      { x: 139, y:   7, made: false, zone: "mr" },
      { x: 157, y:   6, made: false, zone: "mr" },
      { x: 138, y:  35, made: false, zone: "mr" },
      { x: 139, y:  14, made: false, zone: "mr" },
      { x: 155, y:  25, made: false, zone: "mr" },
      { x:  88, y:  38, made: true, zone: "pnt" },
      { x:  96, y:  16, made: true, zone: "pnt" },
      { x:  87, y:  32, made: true, zone: "pnt" },
      { x: 111, y:  31, made: true, zone: "pnt" },
      { x:  85, y:  25, made: true, zone: "pnt" },
      { x:  82, y:  21, made: true, zone: "pnt" },
      { x:  98, y:  15, made: true, zone: "pnt" },
      { x: 100, y:  10, made: true, zone: "pnt" },
      { x: 103, y:  14, made: true, zone: "pnt" },
      { x:  86, y:   7, made: true, zone: "pnt" },
      { x: 113, y:  20, made: true, zone: "pnt" },
      { x:  87, y:  39, made: true, zone: "pnt" },
      { x: 102, y:  25, made: true, zone: "pnt" },
      { x:  91, y:  33, made: true, zone: "pnt" },
      { x: 110, y:  13, made: true, zone: "pnt" },
      { x: 105, y:  22, made: true, zone: "pnt" },
      { x: 109, y:  27, made: true, zone: "pnt" },
      { x: 104, y:  21, made: true, zone: "pnt" },
      { x:  80, y:  30, made: true, zone: "pnt" },
      { x:  94, y:  33, made: true, zone: "pnt" },
      { x:  91, y:  14, made: true, zone: "pnt" },
      { x: 102, y:   7, made: true, zone: "pnt" },
      { x: 105, y:  38, made: true, zone: "pnt" },
      { x: 105, y:   7, made: true, zone: "pnt" },
      { x:  74, y:  38, made: true, zone: "pnt" },
      { x:  87, y:  25, made: true, zone: "pnt" },
      { x:  75, y:  20, made: true, zone: "pnt" },
      { x: 115, y:  37, made: true, zone: "pnt" },
      { x:  87, y:  34, made: true, zone: "pnt" },
      { x: 108, y:  35, made: true, zone: "pnt" },
      { x:  73, y:  28, made: true, zone: "pnt" },
      { x:  74, y:  40, made: true, zone: "pnt" },
      { x:  81, y:   7, made: true, zone: "pnt" },
      { x: 116, y:  28, made: true, zone: "pnt" },
      { x:  77, y:  12, made: true, zone: "pnt" },
      { x: 113, y:  15, made: true, zone: "pnt" },
      { x:  85, y:  38, made: true, zone: "pnt" },
      { x: 103, y:  28, made: true, zone: "pnt" },
      { x:  89, y:  22, made: true, zone: "pnt" },
      { x: 116, y:   5, made: true, zone: "pnt" },
      { x: 108, y:   8, made: true, zone: "pnt" },
      { x:  83, y:  25, made: true, zone: "pnt" },
      { x: 107, y:  14, made: true, zone: "pnt" },
      { x: 103, y:  35, made: true, zone: "pnt" },
      { x:  96, y:   5, made: true, zone: "pnt" },
      { x:  73, y:  18, made: false, zone: "pnt" },
      { x:  92, y:  13, made: false, zone: "pnt" },
      { x:  93, y:   8, made: false, zone: "pnt" },
      { x:  89, y:  14, made: false, zone: "pnt" },
      { x: 102, y:  20, made: false, zone: "pnt" },
      { x: 107, y:  32, made: false, zone: "pnt" },
      { x: 108, y:  40, made: false, zone: "pnt" },
      { x:  73, y:   8, made: false, zone: "pnt" },
      { x:  82, y:  38, made: false, zone: "pnt" },
      { x:  87, y:  25, made: false, zone: "pnt" },
      { x: 115, y:  38, made: false, zone: "pnt" },
      { x: 114, y:  39, made: false, zone: "pnt" },
      { x:  80, y:   7, made: false, zone: "pnt" },
      { x:  92, y:  28, made: false, zone: "pnt" },
      { x:  99, y:   8, made: false, zone: "pnt" },
      { x: 107, y:   6, made: false, zone: "pnt" },
      { x:  76, y:  32, made: false, zone: "pnt" },
      { x: 111, y:   7, made: false, zone: "pnt" },
      { x:  79, y:  25, made: false, zone: "pnt" },
      { x:  73, y:  40, made: false, zone: "pnt" },
      { x:  80, y:  31, made: false, zone: "pnt" },
      { x: 114, y:  36, made: false, zone: "pnt" },
      { x:  77, y:  12, made: false, zone: "pnt" },
      { x:  75, y:  24, made: false, zone: "pnt" },
      { x: 105, y:  21, made: false, zone: "pnt" },
      { x: 112, y:  14, made: false, zone: "pnt" },
      { x: 115, y:  37, made: false, zone: "pnt" },
      { x:  86, y:  19, made: false, zone: "pnt" },
      { x:  81, y:  22, made: false, zone: "pnt" },
      { x: 100, y:  18, made: false, zone: "pnt" },
      { x: 115, y:  24, made: false, zone: "pnt" },
      { x: 114, y:   8, made: false, zone: "pnt" },
      { x:  87, y:  15, made: false, zone: "pnt" },
      { x: 100, y:  31, made: false, zone: "pnt" },
      { x:  72, y:  16, made: false, zone: "pnt" },
      { x: 103, y:  33, made: false, zone: "pnt" },
      { x: 109, y:  36, made: false, zone: "pnt" },
      { x:  88, y:   9, made: false, zone: "pnt" },
      { x: 116, y:   4, made: false, zone: "pnt" },
      { x:  82, y:  15, made: false, zone: "pnt" },
      { x: 117, y:  31, made: false, zone: "pnt" },
      { x: 114, y:   9, made: false, zone: "pnt" },
      { x: 113, y:  11, made: false, zone: "pnt" },
      { x: 100, y:   9, made: false, zone: "pnt" },
    ],
    zoneBreakdown: [
      { id: "lc",  name: "L Corner 3", made: 4,  att: 8,  delta: +5,  pct50: 50, pct7d: [40, 45, 38, 50, 50] },
      { id: "lw",  name: "L Wing 3",   made: 6,  att: 19, delta: -8,  pct50: 32, pct7d: [44, 40, 36, 32, 32] },
      { id: "top", name: "Top 3",      made: 8,  att: 18, delta: +2,  pct50: 44, pct7d: [40, 38, 42, 44, 44] },
      { id: "rw",  name: "R Wing 3",   made: 16, att: 22, delta: +24, pct50: 73, pct7d: [42, 50, 58, 65, 73] },
      { id: "rc",  name: "R Corner 3", made: 2,  att: 7,  delta: -10, pct50: 29, pct7d: [40, 38, 30, 28, 29] },
      { id: "mid", name: "Mid-range",  made: 8,  att: 26, delta: -6,  pct50: 31, pct7d: [38, 36, 33, 30, 31] },
      { id: "pnt", name: "Paint",      made: 45, att: 89, delta: +3,  pct50: 51, pct7d: [48, 49, 50, 51, 51] },
    ],
    drillRecs: {
      lc:  [{ id: "d1", name: "Corner 3 lock-in", reps: 10, level: "STD" }, { id: "d2", name: "Catch & shoot · corner", reps: 12, level: "STD" }],
      lw:  [{ id: "d3", name: "Wing 3 elbow drill", reps: 10, level: "INTRO" }, { id: "d4", name: "Pull-up · left wing", reps: 8, level: "STD" }, { id: "d5", name: "Step-back · left", reps: 6, level: "ADV" }],
      top: [{ id: "d6", name: "Top of key catch & shoot", reps: 10, level: "STD" }, { id: "d7", name: "Pick & pop · top", reps: 8, level: "STD" }],
      rw:  [{ id: "d8", name: "Wing 3 maintenance", reps: 8, level: "STD" }, { id: "d9", name: "Movement 3 · right", reps: 10, level: "ADV" }],
      rc:  [{ id: "d10", name: "Corner 3 lock-in", reps: 10, level: "STD" }, { id: "d11", name: "Catch & shoot · right corner", reps: 12, level: "INTRO" }, { id: "d12", name: "Step-out · baseline", reps: 8, level: "STD" }],
      mid: [{ id: "d13", name: "Mid-range pull-up", reps: 12, level: "INTRO" }, { id: "d14", name: "Elbow jumper rhythm", reps: 10, level: "STD" }, { id: "d15", name: "Free throw rhythm", reps: 10, level: "STD" }],
      pnt: [{ id: "d16", name: "Floater drill", reps: 8, level: "STD" }, { id: "d17", name: "Finishing through contact", reps: 6, level: "ADV" }],
    },
  },

  cold: {
    label: "Last 7 days",
    fg: 33,
    fgDelta: -8,
    made: 53,
    att: 161,
    sessions: 4,
    pps: 0.78,
    bestStreak: 3,
    verdict: "Mid-range never found a rhythm.",
    hotZone: "lc",
    shots: [
      { x:   4, y:   8, made: true, zone: "lc" },
      { x:   8, y:  11, made: true, zone: "lc" },
      { x:   9, y:  10, made: true, zone: "lc" },
      { x:   2, y:   6, made: true, zone: "lc" },
      { x:   6, y:  12, made: true, zone: "lc" },
      { x:   4, y:  12, made: false, zone: "lc" },
      { x:   6, y:   6, made: false, zone: "lc" },
      { x:   7, y:  11, made: false, zone: "lc" },
      { x:   7, y:  12, made: false, zone: "lc" },
      { x:  19, y:  43, made: true, zone: "lw" },
      { x:  21, y:  48, made: true, zone: "lw" },
      { x:  22, y:  66, made: true, zone: "lw" },
      { x:   2, y:  42, made: true, zone: "lw" },
      { x:  13, y:  40, made: false, zone: "lw" },
      { x:  24, y:  49, made: false, zone: "lw" },
      { x:  27, y:  53, made: false, zone: "lw" },
      { x:   5, y:  31, made: false, zone: "lw" },
      { x:   1, y:  62, made: false, zone: "lw" },
      { x:   3, y:  59, made: false, zone: "lw" },
      { x:  32, y:  67, made: false, zone: "lw" },
      { x:   4, y:  23, made: false, zone: "lw" },
      { x:  20, y:  50, made: false, zone: "lw" },
      { x:   2, y:  59, made: false, zone: "lw" },
      { x:  22, y:  71, made: false, zone: "lw" },
      { x:  47, y:  71, made: false, zone: "lw" },
      { x:  83, y:  96, made: true, zone: "top" },
      { x: 104, y: 104, made: true, zone: "top" },
      { x:  80, y: 108, made: true, zone: "top" },
      { x: 112, y: 112, made: true, zone: "top" },
      { x:  90, y: 104, made: true, zone: "top" },
      { x: 105, y: 100, made: false, zone: "top" },
      { x:  90, y:  80, made: false, zone: "top" },
      { x:  72, y:  91, made: false, zone: "top" },
      { x:  84, y:  86, made: false, zone: "top" },
      { x:  99, y:  89, made: false, zone: "top" },
      { x:  84, y: 118, made: false, zone: "top" },
      { x:  88, y:  91, made: false, zone: "top" },
      { x: 100, y:  75, made: false, zone: "top" },
      { x:  99, y: 117, made: false, zone: "top" },
      { x:  85, y: 106, made: false, zone: "top" },
      { x:  83, y: 109, made: false, zone: "top" },
      { x:  72, y: 100, made: false, zone: "top" },
      { x:  85, y:  90, made: false, zone: "top" },
      { x: 162, y:  68, made: true, zone: "rw" },
      { x: 188, y:  22, made: true, zone: "rw" },
      { x: 184, y:  49, made: true, zone: "rw" },
      { x: 188, y:  39, made: true, zone: "rw" },
      { x: 187, y:  68, made: true, zone: "rw" },
      { x: 168, y:  60, made: true, zone: "rw" },
      { x: 153, y:  63, made: false, zone: "rw" },
      { x: 151, y:  71, made: false, zone: "rw" },
      { x: 183, y:  44, made: false, zone: "rw" },
      { x: 181, y:  37, made: false, zone: "rw" },
      { x: 173, y:  47, made: false, zone: "rw" },
      { x: 180, y:  18, made: false, zone: "rw" },
      { x: 188, y:  65, made: false, zone: "rw" },
      { x: 183, y:  56, made: false, zone: "rw" },
      { x: 179, y:  59, made: false, zone: "rw" },
      { x: 161, y:  55, made: false, zone: "rw" },
      { x: 184, y:  35, made: false, zone: "rw" },
      { x: 185, y:  25, made: false, zone: "rw" },
      { x: 180, y:  56, made: false, zone: "rw" },
      { x: 184, y:   4, made: true, zone: "rc" },
      { x: 183, y:   5, made: true, zone: "rc" },
      { x: 186, y:   9, made: false, zone: "rc" },
      { x: 184, y:   3, made: false, zone: "rc" },
      { x: 189, y:   4, made: false, zone: "rc" },
      { x: 185, y:   5, made: false, zone: "rc" },
      { x: 187, y:   7, made: false, zone: "rc" },
      { x: 188, y:   7, made: false, zone: "rc" },
      { x:  33, y:   6, made: true, zone: "ml" },
      { x:  52, y:  35, made: true, zone: "ml" },
      { x:  40, y:   5, made: false, zone: "ml" },
      { x:  48, y:  10, made: false, zone: "ml" },
      { x:  62, y:  38, made: false, zone: "ml" },
      { x:  50, y:   8, made: false, zone: "ml" },
      { x:  55, y:  18, made: false, zone: "ml" },
      { x:  45, y:  30, made: false, zone: "ml" },
      { x:  38, y:  27, made: false, zone: "ml" },
      { x:  60, y:  25, made: false, zone: "ml" },
      { x:  48, y:  12, made: false, zone: "ml" },
      { x:  49, y:  18, made: false, zone: "ml" },
      { x: 143, y:  10, made: true, zone: "mr" },
      { x: 150, y:   5, made: true, zone: "mr" },
      { x: 126, y:   7, made: false, zone: "mr" },
      { x: 128, y:  38, made: false, zone: "mr" },
      { x: 150, y:  32, made: false, zone: "mr" },
      { x: 148, y:  37, made: false, zone: "mr" },
      { x: 143, y:  24, made: false, zone: "mr" },
      { x: 140, y:   8, made: false, zone: "mr" },
      { x: 149, y:  32, made: false, zone: "mr" },
      { x: 135, y:  18, made: false, zone: "mr" },
      { x: 140, y:  21, made: false, zone: "mr" },
      { x: 141, y:  32, made: false, zone: "mr" },
      { x:  89, y:   5, made: true, zone: "pnt" },
      { x: 118, y:   5, made: true, zone: "pnt" },
      { x: 117, y:  24, made: true, zone: "pnt" },
      { x: 116, y:  17, made: true, zone: "pnt" },
      { x:  79, y:  16, made: true, zone: "pnt" },
      { x:  99, y:  38, made: true, zone: "pnt" },
      { x:  84, y:  22, made: true, zone: "pnt" },
      { x:  92, y:  32, made: true, zone: "pnt" },
      { x: 118, y:  33, made: true, zone: "pnt" },
      { x:  80, y:  32, made: true, zone: "pnt" },
      { x:  72, y:  30, made: true, zone: "pnt" },
      { x:  88, y:   9, made: true, zone: "pnt" },
      { x:  90, y:  31, made: true, zone: "pnt" },
      { x:  88, y:  23, made: true, zone: "pnt" },
      { x: 109, y:  39, made: true, zone: "pnt" },
      { x:  94, y:   5, made: true, zone: "pnt" },
      { x:  78, y:  14, made: true, zone: "pnt" },
      { x:  92, y:  31, made: true, zone: "pnt" },
      { x: 110, y:  37, made: true, zone: "pnt" },
      { x:  87, y:  20, made: true, zone: "pnt" },
      { x: 102, y:  13, made: true, zone: "pnt" },
      { x: 100, y:  31, made: true, zone: "pnt" },
      { x:  77, y:  34, made: true, zone: "pnt" },
      { x:  91, y:  14, made: true, zone: "pnt" },
      { x: 110, y:  16, made: true, zone: "pnt" },
      { x:  98, y:  24, made: true, zone: "pnt" },
      { x:  77, y:  26, made: true, zone: "pnt" },
      { x:  82, y:   5, made: false, zone: "pnt" },
      { x: 111, y:  14, made: false, zone: "pnt" },
      { x:  87, y:  18, made: false, zone: "pnt" },
      { x: 106, y:  23, made: false, zone: "pnt" },
      { x: 118, y:  23, made: false, zone: "pnt" },
      { x: 102, y:  36, made: false, zone: "pnt" },
      { x: 101, y:  25, made: false, zone: "pnt" },
      { x:  93, y:  15, made: false, zone: "pnt" },
      { x:  88, y:  33, made: false, zone: "pnt" },
      { x:  96, y:  21, made: false, zone: "pnt" },
      { x:  80, y:  14, made: false, zone: "pnt" },
      { x: 114, y:   5, made: false, zone: "pnt" },
      { x: 107, y:  34, made: false, zone: "pnt" },
      { x: 117, y:   5, made: false, zone: "pnt" },
      { x: 110, y:  21, made: false, zone: "pnt" },
      { x: 106, y:  18, made: false, zone: "pnt" },
      { x: 105, y:  23, made: false, zone: "pnt" },
      { x:  81, y:  26, made: false, zone: "pnt" },
      { x:  90, y:  33, made: false, zone: "pnt" },
      { x: 107, y:  33, made: false, zone: "pnt" },
      { x: 112, y:  31, made: false, zone: "pnt" },
      { x:  88, y:  37, made: false, zone: "pnt" },
      { x:  89, y:  30, made: false, zone: "pnt" },
      { x:  92, y:  22, made: false, zone: "pnt" },
      { x: 112, y:  15, made: false, zone: "pnt" },
      { x: 104, y:  28, made: false, zone: "pnt" },
      { x:  95, y:  20, made: false, zone: "pnt" },
      { x: 103, y:  39, made: false, zone: "pnt" },
      { x: 116, y:   6, made: false, zone: "pnt" },
      { x: 103, y:   9, made: false, zone: "pnt" },
      { x:  79, y:  13, made: false, zone: "pnt" },
      { x: 114, y:  13, made: false, zone: "pnt" },
      { x: 101, y:  11, made: false, zone: "pnt" },
      { x:  92, y:  36, made: false, zone: "pnt" },
      { x:  86, y:  20, made: false, zone: "pnt" },
      { x:  98, y:  16, made: false, zone: "pnt" },
      { x: 111, y:  13, made: false, zone: "pnt" },
      { x: 103, y:  19, made: false, zone: "pnt" },
      { x: 103, y:  38, made: false, zone: "pnt" },
      { x: 105, y:  26, made: false, zone: "pnt" },
    ],
    zoneBreakdown: [
      { id: "lc",  name: "L Corner 3", made: 5,  att: 9,  delta: +14, pct50: 56, pct7d: [42, 45, 50, 53, 56] },
      { id: "lw",  name: "L Wing 3",   made: 4,  att: 16, delta: -12, pct50: 25, pct7d: [40, 35, 30, 28, 25] },
      { id: "top", name: "Top 3",      made: 5,  att: 18, delta: -8,  pct50: 28, pct7d: [38, 34, 32, 30, 28] },
      { id: "rw",  name: "R Wing 3",   made: 6,  att: 19, delta: -6,  pct50: 32, pct7d: [40, 38, 35, 33, 32] },
      { id: "rc",  name: "R Corner 3", made: 2,  att: 8,  delta: -3,  pct50: 25, pct7d: [30, 28, 26, 25, 25] },
      { id: "mid", name: "Mid-range",  made: 4,  att: 24, delta: -22, pct50: 17, pct7d: [40, 30, 22, 18, 17] },
      { id: "pnt", name: "Paint",      made: 27, att: 67, delta: -2,  pct50: 40, pct7d: [44, 42, 41, 40, 40] },
    ],
    drillRecs: null, // assigned below
  },
};

// share drill recs across scenarios
window.TL_DATA.cold.drillRecs = window.TL_DATA.hot.drillRecs;

// ── Sessions list ────────────────────────────────
window.TL_SESSIONS = [
  {
    id: "s5", date: "Today · 6:42 PM",  group: "this-week",
    fg: 67, made: 22, att: 33, durationMin: 28, durationSec: 14,
    delta: +9, bestZone: "R Wing 3", bestZoneFg: 78,
    drills: [
      { name: "Corner 3 lock-in",      reps: 10, made: 7, fg: 70 },
      { name: "Catch & shoot · wing",  reps: 8,  made: 6, fg: 75 },
      { name: "Pull-up mid-range",     reps: 8,  made: 3, fg: 38 },
      { name: "Free throw rhythm",     reps: 7,  made: 6, fg: 86 },
    ],
    thumb: "rw-hot",
  },
  {
    id: "s4", date: "Mon · 7:10 PM", group: "this-week",
    fg: 52, made: 17, att: 33, durationMin: 32, durationSec: 4,
    delta: +3, bestZone: "Top 3", bestZoneFg: 60,
    drills: [
      { name: "Top of key catch & shoot", reps: 10, made: 6, fg: 60 },
      { name: "Pick & pop · top",         reps: 8,  made: 5, fg: 63 },
      { name: "Pull-up mid-range",        reps: 10, made: 3, fg: 30 },
      { name: "Free throw rhythm",        reps: 5,  made: 3, fg: 60 },
    ],
    thumb: "balanced",
  },
  {
    id: "s3", date: "Sat · 11:02 AM", group: "this-week",
    fg: 38, made: 14, att: 37, durationMin: 24, durationSec: 50,
    delta: -12, bestZone: "Paint", bestZoneFg: 56,
    drills: [
      { name: "Floater drill",            reps: 8,  made: 5, fg: 63 },
      { name: "Mid-range pull-up",        reps: 12, made: 3, fg: 25 },
      { name: "Wing 3 elbow drill",       reps: 10, made: 3, fg: 30 },
      { name: "Free throw rhythm",        reps: 7,  made: 3, fg: 43 },
    ],
    thumb: "cold",
  },
  {
    id: "s2", date: "Thu · 6:30 PM", group: "last-week",
    fg: 41, made: 13, att: 32, durationMin: 26, durationSec: 18,
    delta: -4, bestZone: "L Corner 3", bestZoneFg: 50,
    drills: [
      { name: "Corner 3 lock-in",         reps: 10, made: 5, fg: 50 },
      { name: "Wing 3 elbow drill",       reps: 10, made: 4, fg: 40 },
      { name: "Mid-range pull-up",        reps: 8,  made: 2, fg: 25 },
      { name: "Floater drill",            reps: 4,  made: 2, fg: 50 },
    ],
    thumb: "balanced",
  },
  {
    id: "s1", date: "Mon · 7:45 PM", group: "last-week",
    fg: 45, made: 12, att: 27, durationMin: 22, durationSec: 40,
    delta: +1, bestZone: "Top 3", bestZoneFg: 58,
    drills: [
      { name: "Top of key catch & shoot", reps: 8, made: 5, fg: 63 },
      { name: "Catch & shoot · wing",     reps: 8, made: 3, fg: 38 },
      { name: "Pull-up mid-range",        reps: 6, made: 2, fg: 33 },
      { name: "Free throw rhythm",        reps: 5, made: 2, fg: 40 },
    ],
    thumb: "balanced",
  },
];
